name: Update version file

on:
    push:
        tags:
            - "*"

jobs:
    update-version:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Find branch containing the tag
                id: find_branch
                run: |
                    TAG=$(echo "${GITHUB_REF#refs/tags/}")
                    COMMIT=$(git rev-parse $TAG)
                    BRANCH=$(git for-each-ref --format='%(refname:short)' refs/heads/ | while read branch; do
                        if git merge-base --is-ancestor $COMMIT refs/heads/$branch; then
                            echo $branch
                            break
                        fi
                    done)
                    if [ -z "$BRANCH" ]; then
                        echo "No branch found for tag $TAG"
                        exit 1
                    fi
                    echo "branch=$BRANCH" >> $GITHUB_ENV

            -   name: Get the tag
                run: |
                    echo "${GITHUB_REF#refs/tags/}" > version.txt

            -   name: Commit and push the updated version file
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git add version.txt
                    git commit -m "Update version.txt to ${GITHUB_REF#refs/tags/}"
                    git push origin HEAD:refs/heads/${{ env.branch }}
