name: Update version file

on:
    push:
        tags:
            - "*"

jobs:
    update-version:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Find branch containing the tag
                id: find_branch
                run: |
                    TAG=$(echo "${GITHUB_REF#refs/tags/}")
                    BRANCH=$(git branch --all --contains $TAG | grep -v 'remotes/origin/HEAD' | grep 'remotes/origin/' | head -n 1 | sed 's/remotes\/origin\///')
                    echo "branch=$BRANCH" >> $GITHUB_ENV

            -   name: Get the tag
                run: |
                    echo "${GITHUB_REF#refs/tags/}" > version.txt

            -   name: Commit and push the updated version file
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git add version.txt
                    git commit -m "Update version.txt to ${GITHUB_REF#refs/tags/}"
                    git push origin HEAD:refs/heads/${{ env.branch }}
